### ISSUE TITLE
Apparent Magnitudes

### ISSUE THREAD

**Issue by rprollins** [cosmiclens/forward#3]
Calculate apparent magnitudes for a galaxy SED in a set of filters.

**Comment by ntessore** [comment]
The first step is #7 where the integration of the SED is performed.

The second step would be designing a good interface for 

- [ ] the cosmological dependence via the luminosity distance,
- [ ] the conversion to magnitudes via a reference SED,
- [ ] normalisation to a given magnitude in a given band.

**Comment by ntessore** [comment]
Closed by #7 .
